question_data = [
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
                      "question": "The &#039;Squaring the Circle&#039; problem is solvable.", "correct_answer": "False",
                      "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Sports",
                                                       "question": "Peyton Manning retired after winning Super Bowl XLIX.",
                                                       "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False",
                      "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy", "category": "Vehicles",
                                                       "question": "The full English name of the car manufacturer BMW is Bavarian Motor Works",
                                                       "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Geography",
                      "question": "Vatican City is a country.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                      "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                      "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "History",
                      "question": "Adolf Hitler was a german soldier in World War I.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]
